version: '3.12'
services:
  
  db: #         Postgres service 
    image: postgres
    # restart: always
    environment: 
      POSTGRES_DB: "fasdb"
      POSTGRES_USER: "fasdbadmin"
      POSTGRES_PASSWORD: "admin"
      ports: 
        -"5432:5432"
      restart: always
  
  web:  # Django service 
      build: . # Build from the current directory 
      

      command: python manage.py runserver 0.0.0.0:8000 # Run the specified command upon start 
      volumes: # Mount the project directory to enable live reloading of code changes   
        - .:/app   
      ports: 
        - "8000:8000" 
       # Expose port 8000 to the host machine -
        
      depends_on: # Wait for the db service to be running before starting web 
        - db   
      env_file: 
        .env # Load environment variables from this file   
      links: # Link containers together so they can communicate with each other 
      -  db  

