# Generated by Django 3.2.9 on 2023-02-09 18:50

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('base', '0002_alter_document_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='document',
            name='law',
            field=models.ManyToManyField(blank=True, related_name='laws', to='base.Law', verbose_name='Закон'),
        ),
    ]
